import {FeatureState} from "../types/types";

export const INITIAL_STATE: FeatureState = {
  features: [
    {
      featureId: 1,
      parentId: null,
      path: "",
      name: "Storage",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 2,
      parentId: null,
      path: "",
      name: "Movies",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 3,
      parentId: null,
      path: "",
      name: "Shopping",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 4,
      parentId: 1,
      path: "1",
      name: "Buy",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 5,
      parentId: 1,
      path: "1",
      name: "View",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 6,
      parentId: 1,
      path: "1",
      name: "Subscription type",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 7,
      parentId: 2,
      path: "2",
      name: "VIP",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 8,
      parentId: 2,
      path: "2",
      name: "Download",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 9,
      parentId: 2,
      path: "2",
      name: "Rent",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 10,
      parentId: 3,
      path: "3",
      name: "Prime",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 11,
      parentId: 3,
      path: "3",
      name: "Supermarket",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 12,
      parentId: 3,
      path: "3",
      name: "Books",
      sum: 0,
      expanded: false,
      checked: false,
    },
    {
      featureId: 13,
      parentId: 4,
      path: "1.4",
      name: "Buy 100GB",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 14,
      parentId: 4,
      path: "1.4",
      name: "Buy 1TB",
      price: 100,
      expanded: false,
      checked: false,
    },
    {
      featureId: 15,
      parentId: 5,
      path: "1.5",
      name: "Photo Album",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 16,
      parentId: 5,
      path: "1.5",
      name: "View videos in original quality",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 17,
      parentId: 6,
      path: "1.6",
      name: "Personal use",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 18,
      parentId: 6,
      path: "1.6",
      name: "Upto 4 users",
      price: 20,
      expanded: false,
      checked: false,
    },
    {
      featureId: 19,
      parentId: 7,
      path: "2.7",
      name: "View in 4k Quality",
      price: 20,
      expanded: false,
      checked: false,
    },
    {
      featureId: 20,
      parentId: 7,
      path: "2.7",
      name: "View in 8k Quality",
      price: 50,
      expanded: false,
      checked: false,
    },
    {
      featureId: 21,
      parentId: 8,
      path: "2.8",
      name: "Maximum downloads up to 4 movies a month",
      price: 20,
      expanded: false,
      checked: false,
    },
    {
      featureId: 22,
      parentId: 8,
      path: "2.8",
      name: "Maximum downloads up to 10 movies a month",
      price: 40,
      expanded: false,
      checked: false,
    },
    {
      featureId: 23,
      parentId: 9,
      path: "2.9",
      name: "10 movie rents per month",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 24,
      parentId: 9,
      path: "2.9",
      name: "unlimited rentals",
      price: 40,
      expanded: false,
      checked: false,
    },
    {
      featureId: 25,
      parentId: 10,
      path: "3.10",
      name: "Free Delivery",
      price: 40,
      expanded: false,
      checked: false,
    },
    {
      featureId: 26,
      parentId: 10,
      path: "3.10",
      name: "Same day Delivery",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 27,
      parentId: 11,
      path: "3.11",
      name: "Fresh Groceries",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 28,
      parentId: 11,
      path: "3.11",
      name: "Home Center",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 29,
      parentId: 12,
      path: "3.12",
      name: "2 Rentals a Month",
      price: 10,
      expanded: false,
      checked: false,
    },
    {
      featureId: 30,
      parentId: 12,
      path: "3.12",
      name: "4 Rentals a Month",
      price: 15,
      expanded: false,
      checked: false,
    },
  ],
};
